<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE definitions [<!ENTITY xxe SYSTEM "file:///etc/gubbins2" >]>
<wsdl:definitions targetNamespace="uri:bdn" xmlns="uri:bdn" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:binding name="test" type="TERRY_2_PortType_0">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayHello">
    &xxe;
      <soap:operation soapAction="sayTerry"/>
      <wsdl:input>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:examples:helloservice"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:examples:helloservice"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>
